# Generated by Django 5.2.5 on 2025-08-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('website_link', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=300)),
                ('email', models.TextField(max_length=50)),
                ('phone', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='main_app/static/uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
