# Generated by Django 5.2.5 on 2025-08-27 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_university_remove_question_user_delete_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('duration', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('requirements', models.TextField()),
                ('resources_link', models.TextField(max_length=300)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.university')),
                ('users_favorited', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.program')),
            ],
        ),
    ]
