# Generated by Django 5.2.5 on 2025-08-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_question_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='program',
        ),
    ]
