# Generated by Django 5.2.5 on 2025-08-27 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_question_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.program'),
            preserve_default=False,
        ),
    ]
