# Generated by Django 5.2.5 on 2025-08-27 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_question_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main_app.program'),
        ),
    ]
