# Generated by Django 5.2.5 on 2025-08-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_question_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='university',
            name='phone',
            field=models.CharField(),
        ),
    ]
