# Generated by Django 5.2.5 on 2025-08-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_university_latitude_university_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='universities/'),
        ),
    ]
